Repository woowa-techcamp-2020/todo-9, pull requests merged in 2020-07, with the labels that each got.

#3 Dev
  .prettierrc
  .vscode/settings.json
  .vscode/typescript.code-snippets
  client/.gitignore
  server/.gitignore
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/index.ts
  server/tsconfig.json
Labels: backend, environment, frontend

#8 Feature/4 woowa react
  a
  client/.gitignore
  client/.vscode/settings.json
  client/babel.config.js
  client/jest.config.js
  client/package-lock.json
  client/package.json
  client/src/App.ts
  client/src/comopents/Header/Header.test.ts
  client/src/comopents/Header/Header.ts
  client/src/index.ts
  client/src/utils/Component.ts
  client/src/utils/__test__/Component.test.ts
  client/src/utils/__test__/defaultElements.test.ts
  client/src/utils/__test__/generateElement.test.ts
  client/src/utils/__test__/renderDom.test.ts
  client/src/utils/defaultElements.ts
  client/src/utils/generateElement.ts
  client/src/utils/renderDom.ts
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
Labels: environment, frontend

#9 Feature/7 mysql setup
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/config/db.ts
  server/src/index.ts
  server/src/public/dist/bundle.js
  server/tsconfig.json
  server/typings.json
Labels: backend, database, environment

#10 Evn/1 fe dev env
  client/.gitignore
  client/.vscode/settings.json
  client/babel.config.js
  client/jest.config.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.ts
  client/src/components/Header/Header.test.ts
  client/src/components/Header/Header.ts
  client/src/components/Header/header.scss
  client/src/components/Header/index.ts
  client/src/index.ts
  client/src/utils/renderDom.ts
  client/src/utils/wooact/Component.ts
  client/src/utils/wooact/__test__/Component.test.ts
  client/src/utils/wooact/__test__/defaultElements.test.ts
  client/src/utils/wooact/__test__/domRenderer.test.ts
  client/src/utils/wooact/__test__/generateElement.test.ts
  client/src/utils/wooact/defaultElements.ts
  client/src/utils/wooact/domRenderer.ts
  client/src/utils/wooact/generateElement.ts
  client/src/utils/wooact/index.ts
  client/webpack.common.js
  client/webpack.dev.js
  server/src/public/bundle.js
  server/src/public/index.html
Labels: environment, frontend

#14 [#11] feat -add script generate wooact boilerplate
  client/create-wooact-component.sh
  client/src/components/Header/Header.ts
Labels: component, feature, frontend

#19 Feature/15 fe modal
  a
  client/babel.config.js
  client/create-wooact-component.sh
  client/package-lock.json
  client/package.json
  client/public/images/woowabros.png
  client/src/App.ts
  client/src/components/App/App.scss
  client/src/components/App/App.test.ts
  client/src/components/App/App.ts
  client/src/components/App/index.ts
  client/src/components/BoxButton/BoxButton.scss
  client/src/components/BoxButton/BoxButton.test.ts
  client/src/components/BoxButton/BoxButton.ts
  client/src/components/BoxButton/index.ts
  client/src/components/BoxInput/BoxInput.scss
  client/src/components/BoxInput/BoxInput.test.ts
  client/src/components/BoxInput/BoxInput.ts
  client/src/components/BoxInput/index.ts
  client/src/components/Header/Header.test.ts
  client/src/components/Header/Header.ts
  client/src/components/Header/header.scss
  client/src/components/Header/index.ts
  client/src/components/IconButton/IconButton.scss
  client/src/components/IconButton/IconButton.test.ts
  client/src/components/IconButton/IconButton.ts
  client/src/components/IconButton/index.ts
  client/src/components/Modal/Modal.scss
  client/src/components/Modal/Modal.test.ts
  client/src/components/Modal/Modal.ts
  client/src/components/Modal/index.ts
  client/src/components/SideBar/SideBar.scss
  client/src/components/SideBar/SideBar.test.ts
  client/src/components/SideBar/SideBar.ts
  client/src/components/SideBar/index.ts
  client/src/components/SideBarItem/SideBarItem.scss
  client/src/components/SideBarItem/SideBarItem.test.ts
  client/src/components/SideBarItem/SideBarItem.ts
  client/src/components/SideBarItem/index.ts
  client/src/index.ts
  client/src/styles/_definitions.scss
  client/src/styles/fonts/Framework7Icons-Regular.eot
  client/src/styles/fonts/Framework7Icons-Regular.ttf
  client/src/styles/fonts/Framework7Icons-Regular.woff
  client/src/styles/fonts/Framework7Icons-Regular.woff2
  client/src/styles/fonts/noto-sans-kr/noto-sans-kr-v12-latin-regular.eot
  client/src/styles/fonts/noto-sans-kr/noto-sans-kr-v12-latin-regular.svg
  client/src/styles/fonts/noto-sans-kr/noto-sans-kr-v12-latin-regular.woff
  client/src/styles/fonts/noto-sans-kr/noto-sans-kr-v12-latin-regular.woff2
  client/src/styles/reset.scss
  client/src/utils/eventsHandler/debouncer.ts
  client/src/utils/wooact/defaultElements.ts
  client/src/utils/wooact/generateElement.ts
  client/src/utils/wooact/index.ts
  client/webpack.common.js
Labels: component, frontend

#22 Feature/17 column markup
  client/public/index.html
  client/src/components/App/App.scss
  client/src/components/App/App.ts
  client/src/components/Column/Column.scss
  client/src/components/Column/Column.test.ts
  client/src/components/Column/Column.ts
  client/src/components/Column/index.ts
  client/src/components/TodoItem/TodoItem.scss
  client/src/components/TodoItem/TodoItem.test.ts
  client/src/components/TodoItem/TodoItem.ts
  client/src/components/TodoItem/index.ts
Labels: component, feature, frontend

#28 Feature/20 add item input
  client/src/components/AddItemInput/AddItemInput.scss
  client/src/components/AddItemInput/AddItemInput.test.ts
  client/src/components/AddItemInput/AddItemInput.ts
  client/src/components/AddItemInput/index.ts
  client/src/components/App/App.ts
  client/src/components/BoxButton/BoxButton.scss
  client/src/components/BoxButton/BoxButton.ts
  client/src/components/BoxInput/BoxInput.scss
  client/src/components/BoxInput/BoxInput.ts
  client/src/components/Column/Column.ts
  client/src/components/Modal/Modal.ts
  client/src/utils/eventsHandler/openModal.ts
  client/src/utils/wooact/generateElement.ts
Labels: component, frontend

#32 Feature/28 item api
  client/package-lock.json
  client/package.json
  client/src/apis/item.ts
  client/src/apis/kanban.ts
  client/src/apis/log.ts
  client/src/components/AddItemInput/AddItemInput.ts
  client/src/components/App/App.ts
  client/src/components/BoxButton/BoxButton.ts
  client/src/components/Column/Column.scss
  client/src/components/TodoItem/TodoItem.scss
  client/src/components/TodoItem/TodoItem.ts
  client/src/utils/fetchWrapper.ts
  client/webpack.common.js
  client/webpack.dev.js
  server/package-lock.json
  server/package.json
  server/src/apis/__test__/item.test.ts
  server/src/apis/__test__/user.test.ts
  server/src/apis/index.ts
  server/src/apis/item.ts
  server/src/apis/kanban.ts
  server/src/apis/log.ts
  server/src/apis/user.ts
  server/src/app.ts
  server/src/config/db.ts
  server/src/index.ts
  server/src/middlewares/validate-body.ts
  server/src/schema/Item.ts
  server/src/schema/Kanban.ts
  server/src/schema/Log.ts
  server/src/schema/User.ts
  server/src/schema/index.ts
  server/src/utils/promiseHandler.ts
  server/src/utils/queryExecuter.ts
Labels: api, backend, component, database, frontend

#35 Feature/33 connect api
  client/src/apis/item.ts
  client/src/apis/kanban.ts
  client/src/components/App/App.ts
  client/src/components/Column/Column.ts
  client/src/components/DashBoard/DashBoard.scss
  client/src/components/DashBoard/DashBoard.test.ts
  client/src/components/DashBoard/DashBoard.ts
  client/src/components/DashBoard/index.ts
  client/src/components/TodoItem/TodoItem.ts
  client/src/utils/fetchWrapper.ts
  server/package-lock.json
  server/package.json
  server/src/apis/kanban.ts
  server/src/app.ts
  server/src/schema/Kanban.ts
  server/src/schema/User.ts
  server/src/schema/types.ts
  server/src/utils/queryExecuter.ts
Labels: api, frontend

#37 Feature/31 [BE] user kanban api
  client/src/apis/item.ts
  client/src/apis/kanban.ts
  client/src/components/App/App.ts
  client/src/components/Column/Column.ts
  client/src/components/DashBoard/DashBoard.scss
  client/src/components/DashBoard/DashBoard.test.ts
  client/src/components/DashBoard/DashBoard.ts
  client/src/components/DashBoard/index.ts
  client/src/components/TodoItem/TodoItem.ts
  server/src/utils/query-executor.ts
Labels: backend, database, feature

#39 Feature/38 [BE] item log api
  server/package-lock.json
  server/package.json
  server/src/apis/__test__/item.test.ts
  server/src/apis/__test__/user.test.ts
  server/src/apis/index.ts
  server/src/apis/item.ts
  server/src/apis/kanban.ts
  server/src/apis/log.ts
  server/src/config/db.ts
  server/src/index.ts
  server/src/schema/Database.ts
  server/src/schema/Item.ts
  server/src/schema/Kanban.ts
  server/src/schema/Log.ts
  server/src/schema/User.ts
  server/src/schema/index.ts
  server/src/schema/types.ts
  server/src/utils/query-executor.ts
Labels: api, backend, feature

#40 Feature/36 drag and drop
  client/src/components/App/App.scss
  client/src/components/App/App.ts
  client/src/components/Column/Column.scss
  client/src/components/Column/Column.ts
  client/src/components/TodoItem/TodoItem.scss
  client/src/components/TodoItem/TodoItem.ts
  client/src/index.ts
  client/src/utils/dragAndDrop.ts
Labels: component, frontend

#44 Feature/42 connect item api
  client/src/apis/item.ts
  client/src/apis/kanban.ts
  client/src/components/AddItemInput/AddItemInput.scss
  client/src/components/AddItemInput/AddItemInput.ts
  client/src/components/BoxInput/BoxInput.ts
  client/src/components/Column/Column.ts
  client/src/components/DashBoard/DashBoard.ts
  client/src/components/TodoItem/TodoItem.scss
  client/src/components/TodoItem/TodoItem.ts
  client/src/styles/reset.scss
  client/src/utils/dragAndDrop.ts
  client/src/utils/fetchWrapper.ts
  client/src/utils/promiseHandler.ts
  server/src/apis/item.ts
  server/src/config/db.ts
  server/src/schema/Item.ts
  server/src/schema/Kanban.ts
Labels: api, component, frontend

#46 Feature/45 connect dnd api
  client/src/apis/kanban.ts
  client/src/utils/dragAndDrop.ts
  server/src/apis/kanban.ts
  server/src/schema/Kanban.ts
Labels: api, component, feature, frontend

#51 Feature/50 input validator
  client/src/components/BoxButton/BoxButton.scss
  client/src/components/BoxButton/BoxButton.ts
  client/src/components/BoxInput/BoxInput.ts
  server/src/apis/item.ts
  server/src/schema/Kanban.ts
  server/src/schema/User.ts
Labels: component

#56 Feature/55 user modal
  client/src/apis/kanban.ts
  client/src/apis/user.ts
  client/src/components/App/App.ts
  client/src/components/Column/Column.ts
  client/src/components/TextInput/TextInput.scss
  client/src/components/TextInput/TextInput.ts
  client/src/components/UserModal/UserModal.scss
  client/src/components/UserModal/UserModal.test.ts
  client/src/components/UserModal/UserModal.ts
  client/src/components/UserModal/index.ts
  client/src/index.ts
  server/src/apis/user.ts
Labels: feature, frontend
